base_model: mistralai/Mistral-7B-Instruct-v0.3
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_4bit: true
bnb_4bit_compute_dtype: bfloat16
bnb_4bit_use_double_quant: true
bnb_4bit_quant_type: nf4

adapter: lora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05

lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

datasets:
  - path: /sciclone/scr10/gzdata440/wm_bot/data/fine_tuning/formatted_fine_tuning_data.jsonl
    type: chat_template
    chat_template: tokenizer_default

# Renamed to avoid using your old Llama 3 tokenized data!
dataset_prepared_path: bot_test_resources/mistral/mistral_prepared
val_set_size: 0.08

# Double check this path! Using an absolute path like /sciclone/scr10/... is safer
output_dir: bot_test_resources/mistral/qlora-out

sequence_len: 2048
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

micro_batch_size: 2

#flash_attention: true

gradient_checkpointing: true
gradient_accumulation_steps: 8

num_epochs: 3
learning_rate: 5e-5

optimizer: paged_adamw_8bit
lr_scheduler: cosine
warmup_ratio: 0.1

train_on_inputs: false
group_by_length: true

max_grad_norm: 1.0

bf16: true
fp16: false

logging_steps: 10
save_steps: 500